# Generated by Django 3.1.4 on 2020-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='age',
            field=models.IntegerField(default=12),
        ),
    ]
