# Generated by Django 3.1.4 on 2021-01-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_treader_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
