# Generated by Django 3.1.4 on 2020-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_auto_20201230_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybook',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
