# Generated by Django 3.1.4 on 2021-01-01 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20210101_0549'),
        ('distributor', '0007_auto_20201231_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderreader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=60)),
                ('tme', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader')),
            ],
        ),
        migrations.CreateModel(
            name='orderbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.book')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.orderreader')),
            ],
        ),
    ]
