# Generated by Django 3.1.4 on 2021-01-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0009_auto_20210101_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
