# Generated by Django 3.1.4 on 2021-01-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20210101_0549'),
        ('distributor', '0010_orderbook_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.coupon'),
        ),
    ]
